TRPOlab3ASPNET/Models/ErrorViewModel.cs
using System;

namespace TRPOlab3ASPNET.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TRPOlab3ASPNET/Models/modelview.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TRPOlab3ASPNET.Controllers;

namespace TRPOlab3ASPNET.Models
{
    public class modelview
    {
        private double _OutR;
        public double OutR
        {
            get { return _OutR; }
            set
            {
                _OutR = value;
               
            }
        }
        private double _InR;
        public double InR
        {
            get { return _InR; }
            set
            {
                _InR = value;
              
            }
        }
        public double S { get { return  0 ; } }


    }
}

TRPOlab3ASPNET/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using TRPOlab3ASPNET.Models;

namespace TRPOlab3ASPNET.Controllers
{
    public class HomeController : Controller
    {
       
        public ActionResult Index()
        {
                   
            return View("Views/Square/Edit");


        }
        [HttpPut]
        public string Edit(double R1, double R2)
        {
            return   "5" ; 
        }

    // GET: da/Edit/5
    [HttpGet]
    public ActionResult Edit(int id)
    {
        return View();
    }
}
}

TRPOlab3ASPNET/Controllers/SquareController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using TRPO3labBib;
using TRPOlab3ASPNET.Models;

namespace TRPOlab3ASPNET.Controllers
{
    public class SquareController : Controller
    {    
        
        // POST: Square/Edit/5
        [HttpPost]
   
        public ActionResult Edit(double R1, double R2 , double S)
        {

            //static double GetSquare(double R1, double R2) => Math.PI * (Math.Pow(R1, 2) - Math.Pow(R2, 2));
            ViewBag.result = 5;/*.GetSq(R1,R2);*/
            return View("Views/Square/Edit");
            

        }
        // GET: da/Edit/5
        [HttpGet]
        public ActionResult Edit(int id)
        {
            return View();
        }      


    }
}

TRPOlab3ASPNET/Views/Home/Index.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <a href="Views/Home/Sq">СОА</a>
</body>
</html>

TRPOlab3ASPNET/Views/Home/Sq.cshtml
@model TRPOlab3ASPNET.Models.modelview
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <form asp-action="">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="OutR" class="control-label"></label>
            <input type="number" name="R1" asp-for="OutR" class="form-control" placeholder="Внешний" />
            <span asp-validation-for="OutR" class="text-danger"></span>
        </div>
        <p>Я ЕБАЛ ЭТО ВСЁ</p>
        <div class="form-group">
            <label asp-for="InR" class="control-label"></label>
            <input type="number" name="R2" asp-for="InR" class="form-control" placeholder="Внутренний" />
            <span asp-validation-for="InR" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="S" class="control-label"></label>
            <input asp-for="S" name="S1" class="form-control" value="@ViewBag.result" placeholder="Результат" />
            <span asp-validation-for="S" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input type="submit" value="Save" class="btn btn-primary" />
        </div>
    </form>
</body>
</html>

TRPOlab3ASPNET/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TRPOlab3ASPNET</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TRPOlab3ASPNET</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Square" asp-action="Edit">КОГДА ВСЕ ЭТО КОНЧИТСЯ</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - TRPOlab3ASPNET - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

TRPOlab3ASPNET/Views/Square/Edit.cshtml
@model TRPOlab3ASPNET.Models.modelview

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>modelview</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group" >
                <label asp-for="OutR" class="control-label"></label>
                <input type="number" name="R1" asp-for="OutR" class="form-control" placeholder="Внешний" />
                <span asp-validation-for="OutR" class="text-danger"></span>
            </div>
            <p >Я ЕБАЛ ЭТО ВСЁ</p>
            <div class="form-group">
                <label asp-for="InR" class="control-label"></label>
                <input type="number" name="R2" asp-for="InR" class="form-control" placeholder="Внутренний" />
                <span asp-validation-for="InR" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="S" class="control-label"></label>
                <input asp-for="S"  name="S1" class="form-control" value="@ViewBag.result" placeholder="Результат"/>
                <span asp-validation-for="S" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
     



    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>